name: Upload Python package

on:
  release:
    types: [published]


jobs:
  ci:
    uses: ./.github/workflows/ci-workflow.yml

  build:
    runs-on: ubuntu-latest
    needs: ci
    permissions:
      actions: read
      contents: read
      id-token: write
    environment:
      name: publish-packages
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Build wheel
        run: make wheel

      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@b7f401de30cb6434a1e19f805ff006643653240e  # v1.8.10
        with:
          skip-existing: true